---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
data:
  git-clone-migrations.sh: |
    cd /opt/appflowy
    git clone --filter=blob:none --sparse https://github.com/AppFlowy-IO/AppFlowy-Cloud.git
    cd AppFlowy-Cloud/
    git sparse-checkout add migrations
    cd migrations/
  db-migrations.sh: |
    cd /opt/appflowy/AppFlowy-Cloud/migrations

    echo "Running migrations with sqlx now!"

    for script in `ls -1 before`; do
        echo -e "Running sql script: $script"
        psql -h $PGHOST -U $PGUSER -p $PGPORT -d $PGDATABASE -f before/$script
    done

    for script in `ls -p | grep -v /`; do
        echo -e "Running sql script: $script"
        psql -h $PGHOST -U $PGUSER -p $PGPORT -d $PGDATABASE -f $script
    done
