apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "appflowy.fullname" . }}-cloud
  labels:
    {{- include "appflowy.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "appflowy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "appflowy.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "appflowy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: APP_ENVIRONMENT
              value: {{ .Values.appflowy.environment }}
            - name: RUST_LOG
              value: {{ .Values.appflowy.rustLog }}
            - name: APP__GOTRUE__ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ include "appflowy.gotrue.secret" . }}
                  key: {{ .Values.gotrue.secretKeys.adminEmail }}
            - name: APP__GOTRUE__ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "appflowy.gotrue.secret" . }}
                  key: {{ .Values.gotrue.secretKeys.adminPassword }}
            - name: APP__GOTRUE__JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "appflowy.gotrue.secret" . }}
                  key: {{ .Values.gotrue.secretKeys.jwtSecret }}
            - name: APP__GOTRUE__EXT_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "appflowy.gotrue.secret" . }}
                  key: {{ .Values.gotrue.secretKeys.externalUrl }}
            {{- if .Values.appflowy.s3.useMinio }}
            - name: APP__S3__USE_MINIO
              value: "true"
            {{- end }}
            - name: APP__S3__AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "appflowy.s3.secret" . }}
                  key: {{ .Values.appflowy.s3.secretKeys.accessKeyId }}
            - name: APP__S3__AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "appflowy.s3.secret" . }}
                  key: {{ .Values.appflowy.s3.secretKeys.secretAccessKey }}
            - name: APP__S3__AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: {{ include "appflowy.s3.secret" . }}
                  key: {{ .Values.appflowy.s3.secretKeys.region }}
            - name: APP__S3__AWS_BUCKET
              valueFrom:
                secretKeyRef:
                  name: {{ include "appflowy.s3.secret" . }}
                  key: {{ .Values.appflowy.s3.secretKeys.bucket }}
            - name: APP__S3__MINIO_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "appflowy.s3.secret" . }}
                  key: {{ .Values.appflowy.s3.secretKeys.endpoint }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
