{{- if or (not .Values.externalDatabase.existingSecret) (not .Values.postgresql.global.postgresql.existingSecret ) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: appflowy-db-secret
data:
  {{- if .Values.postgresql.enabled }}
  host: {{ .Values.postgresql.fullnameOverride }}
  user: {{ .Values.postgresql.global.postgresql.auth.username }}
  {{- if .Values.postgresql.password }}
  password: {{ .Values.postgresql.global.postgresql.auth.password }}
  url: {{- printf "postgres://%s:%s@%s:5432/%s" .Values.postgresql.global.postgresql.auth.username .Values.postgresql.global.postgresql.auth.password .Values.postgresql.fullnameOverride .Values.postgresql.global.postgresql.auth.database }}
  {{- else }}
  url: {{- printf "postgres://%s@%s:5432/%s" .Values.postgresql.global.postgresql.auth.username .Values.postgresql.fullnameOverride .Values.postgresql.global.postgresql.auth.database }}
  {{- end }}
  port: "5432"
  database: {{ .Values.postgresql.global.postgresql.auth.database }}
  {{- end }} {{/** end postgresql.enabled section **/}}
  {{- if .Values.externalDatabase.host }}
  host: {{ .Values.externalDatabase.host }}
  port: {{ .Values.externalDatabase.port }}
  user: {{ .Values.externalDatabase.user }}
  {{- if .Values.externalDatabase.password }}
  password: {{ .Values.externalDatabase.password }}
  url: {{- printf "postgres://%s:%s@%s:%s/%s" .Values.externalDatabase.user .Values.externalDatabase.password .Values.externalDatabase.host .Values.externalDatabase.port .Values.externalDatabase.database }}
  {{- else }}
  url: {{- printf "postgres://%s@%s:%s/%s" .Values.externalDatabase.user .Values.externalDatabase.host .Values.externalDatabase.port .Values.externalDatabase.database }}
  {{- end }}
  database: {{ .Values.externalDatabase.database }}
  {{- end }} {{/** end externalDatabase section **/}}
{{- end }}
