{{- if not (or .Values.externalDatabase.existingSecret .Values.postgresql.global.postgresql.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: appflowy-db-secret
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
data:
  {{- if .Values.postgresql.enabled }}
  host: {{ .Values.postgresql.fullnameOverride }}
  user: {{ .Values.postgresql.global.postgresql.auth.username }}
  {{- if .Values.postgresql.password }}
  password: {{ .Values.postgresql.global.postgresql.auth.password }}
  {{- end }}
  port: "5432"
  database: {{ .Values.postgresql.global.postgresql.auth.database }}
  {{- end }} {{/** end postgresql.enabled section **/}}
  {{- if .Values.externalDatabase.host }}
  host: {{ .Values.externalDatabase.host }}
  port: {{ .Values.externalDatabase.port }}
  user: {{ .Values.externalDatabase.user }}
  {{- if .Values.externalDatabase.password }}
  password: {{ .Values.externalDatabase.password }}
  {{- end }}
  database: {{ .Values.externalDatabase.database }}
  {{- end }} {{/** end externalDatabase section **/}}
{{- end }}
