{{- if not .Values.appflowy.gotrue.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: appflowy-gotrue-secret
data:
  APP__GOTRUE__ADMIN_EMAIL: {{ .Values.appflowy.gotrue.adminEmail }}
  APP__GOTRUE__ADMIN_PASSWORD: {{ .Values.appflowy.gotrue.adminPassword }}
  APP__GOTRUE__EXT_URL: {{ .Values.appflowy.gotrue.extUrl }}
  APP__GOTRUE__JWT_SECRET: {{ .Values.appflowy.gotrue.jwtSecret }}
{{- end }}
