{{- if not .Values.gotrue.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: appflowy-gotrue-secret
data:
  jwtSecret: {{ .Values.gotrue.jwtSecret }}
  externalUrl: {{ .Values.gotrue.externalUrl }}
  adminEmail: {{ .Values.gotrue.adminEmail }}
  adminPassword: {{ .Values.gotrue.adminPassword }}
{{- end }}
