{{- if not (or .Values.externalDatabase.existingSecret .Values.postgresql.global.postgresql.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: appflowy-db-secret
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
data:
  {{- if .Values.postgresql.enabled }}
  host: {{ .Values.postgresql.fullnameOverride | b64enc | quote }}
  user: {{ .Values.postgresql.global.postgresql.auth.username | b64enc | quote }}
  {{- if .Values.postgresql.password }}
  password: {{ .Values.postgresql.global.postgresql.auth.password | b64enc | quote }}
  {{- end }}
  port: {{ print "5432" | b64enc | quote }}
  database: {{ .Values.postgresql.global.postgresql.auth.database | b64enc | quote }}
  {{- end }} {{/** end postgresql.enabled section **/}}
  {{- if .Values.externalDatabase.host }}
  host: {{ .Values.externalDatabase.host | b64enc | quote }}
  port: {{ .Values.externalDatabase.port | b64enc | quote }}
  user: {{ .Values.externalDatabase.user | b64enc | quote }}
  {{- if .Values.externalDatabase.password }}
  password: {{ .Values.externalDatabase.password | b64enc | quote }}
  {{- else }}
  DATABASE_URL: {{ printf "postgres://%s@%s:%s/%s?sslmode=%s&sslrootcert=%s&sslkey=%s&sslcert=%s" .Values.externalDatabase.user .Values.externalDatabase.host .Values.externalDatabase.port .Values.externalDatabase.database .Values.externalDatabase.sslMode .Values.externalDatabase.sslRootCert .Values.externalDatabase.sslKey .Values.externalDatabase.sslCert | b64enc | quote }}
  {{- end }}
  database: {{ .Values.externalDatabase.database | b64enc | quote }}
  {{- end }} {{/** end externalDatabase section **/}}
{{- end }}
