---
apiVersion: v1
kind: Secret
metadata:
  name: appflowy-gotrue-secret
data:
  externalUrl: {{ .Values.gotrue.externalUrl }}
  {{- if not .Values.gotrue.jwt.existingSecret }}
  jwtSecret: {{ .Values.gotrue.jwt.secret }}
  {{- end }}
  {{- if not .Values.gotrue.smtp.existingSecret }}
  adminEmail: {{ .Values.gotrue.smtp.existingSecret }}
  {{- end }}
  {{- if not .Values.appflowy.gotrue.existingSecret }}
  adminPassword: {{ .Values.gotrue.adminPassword }}
  {{- end }}
