---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sql-migrations
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
